version: "3.9"
services:
  rails:
    build: .
    command: /bin/bash -c "rm -f /tmp/server.pid && (bundle check || bundle install) && bundle exec rails db:migrate && bundle exec rails server -b 0.0.0.0 -P /tmp/server.pid"
    env_file: .env
    ports:
      - 3000:3000
    depends_on:
      - postgresql
    volumes:
      - ruby-bundle-cache:/usr/local/bundle
  postgresql:
    image: postgres:13
    environment:
      - POSTGRES_USER=webnote
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=webnote_development
    ports:
      - "5432:5432"
volumes:
  ruby-bundle-cache:
    external: true
